# Site settings
title: Forty
subtitle: by HTML5 UP
email: it_sjd@outlook.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/sjditadmin.github.io" # the subpath of your site, e.g. /blog
url: "https://sjditadmin.github.io/" # the base hostname & protocol for your site
author:
street_address: Changjiu Mansion,NO.99 Shi Ge Zhuang Road,Chaoyang District
city: Beijing
state: CN
zip_code: 100024
country: China	
phone: (86) 18611178501

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
